import type { Response } from 'express'
import PDFDocument from 'pdfkit'
import ExcelJS from 'exceljs'
import path from 'node:path'
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import type { ReportDocument, ReportTable } from './data.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
// backend/src/lib/reports → ../../../assets
const LOGO_PATH = path.resolve(__dirname, '../../../assets/adani-logo.png')

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}

function fmtDateTime(iso: string): string {
  return new Date(iso).toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

function sanitizeFilename(s: string): string {
  return s.replace(/[^a-zA-Z0-9._-]+/g, '_').slice(0, 80)
}

export function reportFilename(doc: ReportDocument, ext: string): string {
  const asset = sanitizeFilename(doc.asset.name)
  return `${asset}_${doc.reportId}_${doc.dateRange.from}_to_${doc.dateRange.to}.${ext}`
}

// ── PDF ────────────────────────────────────────────────────
export function renderPdf(doc: ReportDocument, res: Response): void {
  const pdf = new PDFDocument({
    size: 'A4', margin: 36,
    info: { Title: doc.title, Author: 'Adani UAMS', CreationDate: new Date() },
  })

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', `attachment; filename="${reportFilename(doc, 'pdf')}"`)
  pdf.pipe(res)

  // ── Header ──
  const pageWidth = pdf.page.width - pdf.page.margins.left - pdf.page.margins.right
  const headerTop = pdf.y

  // Logo (medium: ~48px tall, preserves aspect)
  if (fs.existsSync(LOGO_PATH)) {
    try { pdf.image(LOGO_PATH, pdf.page.margins.left, headerTop, { height: 36 }) }
    catch { /* skip on error */ }
  }

  // Title block, right-aligned
  pdf.font('Helvetica-Bold').fontSize(16).fillColor('#111827')
    .text(doc.title, pdf.page.margins.left, headerTop + 4, {
      width: pageWidth, align: 'right',
    })
  pdf.font('Helvetica').fontSize(9).fillColor('#6b7280')
    .text(`${doc.asset.name}${doc.asset.serial ? `  ·  ${doc.asset.serial}` : ''}`, {
      width: pageWidth, align: 'right',
    })
  pdf.text(`Period: ${fmtDate(doc.dateRange.from)} → ${fmtDate(doc.dateRange.to)}`, {
    width: pageWidth, align: 'right',
  })

  pdf.moveDown(1.5)
  // Divider
  const dividerY = pdf.y
  pdf.strokeColor('#e5e7eb').lineWidth(0.5)
    .moveTo(pdf.page.margins.left, dividerY).lineTo(pdf.page.margins.left + pageWidth, dividerY).stroke()
  pdf.moveDown(0.8)

  // ── Tables ──
  if (doc.tables.length === 0 || doc.tables.every(t => t.rows.length === 0)) {
    pdf.font('Helvetica-Oblique').fontSize(11).fillColor('#9ca3af')
      .text('No data available for the selected period.', { align: 'center' })
  } else {
    for (const table of doc.tables) {
      renderPdfTable(pdf, table, pageWidth)
      pdf.moveDown(1)
    }
  }

  // ── Footer (drawn on every page) ──
  const pageRange = pdf.bufferedPageRange()
  for (let i = pageRange.start; i < pageRange.start + pageRange.count; i++) {
    pdf.switchToPage(i)
    const footerY = pdf.page.height - 28
    pdf.font('Helvetica').fontSize(7.5).fillColor('#9ca3af')
      .text(`Generated by ${doc.generatedBy} on ${fmtDateTime(doc.generatedAt)}`,
        pdf.page.margins.left, footerY,
        { width: pageWidth, align: 'left' })
    pdf.text(`Page ${i - pageRange.start + 1} of ${pageRange.count}`,
      pdf.page.margins.left, footerY,
      { width: pageWidth, align: 'right' })
  }

  pdf.end()
}

function renderPdfTable(pdf: PDFKit.PDFDocument, table: ReportTable, pageWidth: number) {
  const left = pdf.page.margins.left
  const totalWidthSpec = table.columns.reduce((s, c) => s + (c.width ?? 80), 0)
  const scale = pageWidth / totalWidthSpec
  const colWidths = table.columns.map(c => (c.width ?? 80) * scale)

  // Section title
  pdf.font('Helvetica-Bold').fontSize(11).fillColor('#111827').text(table.title, left, pdf.y)
  pdf.moveDown(0.4)

  if (table.rows.length === 0) {
    pdf.font('Helvetica-Oblique').fontSize(9).fillColor('#9ca3af').text('(No records)', left)
    pdf.moveDown(0.4)
    return
  }

  // Header row
  let y = pdf.y
  pdf.rect(left, y, pageWidth, 18).fill('#f3f4f6')
  pdf.font('Helvetica-Bold').fontSize(8).fillColor('#374151')
  let x = left
  for (let i = 0; i < table.columns.length; i++) {
    const c = table.columns[i]
    pdf.text(c.label, x + 4, y + 5, { width: colWidths[i] - 8, align: c.align ?? 'left', lineBreak: false, ellipsis: true })
    x += colWidths[i]
  }
  y += 18
  pdf.y = y

  // Data rows
  pdf.font('Helvetica').fontSize(8).fillColor('#1f2937')
  for (const row of table.rows) {
    // Page break check
    if (pdf.y + 16 > pdf.page.height - pdf.page.margins.bottom - 30) {
      pdf.addPage()
      y = pdf.page.margins.top
      pdf.y = y
      // Repeat header on new page
      pdf.rect(left, y, pageWidth, 18).fill('#f3f4f6')
      pdf.font('Helvetica-Bold').fontSize(8).fillColor('#374151')
      x = left
      for (let i = 0; i < table.columns.length; i++) {
        const c = table.columns[i]
        pdf.text(c.label, x + 4, y + 5, { width: colWidths[i] - 8, align: c.align ?? 'left', lineBreak: false, ellipsis: true })
        x += colWidths[i]
      }
      y += 18
      pdf.y = y
      pdf.font('Helvetica').fontSize(8).fillColor('#1f2937')
    }

    x = left
    for (let i = 0; i < table.columns.length; i++) {
      const c = table.columns[i]
      const val = row[c.key]
      const text = val === null || val === undefined ? '' : String(val)
      pdf.text(text, x + 4, y + 4, {
        width: colWidths[i] - 8,
        align: c.align ?? 'left',
        lineBreak: false,
        ellipsis: true,
      })
      x += colWidths[i]
    }
    // Bottom border
    pdf.strokeColor('#f3f4f6').lineWidth(0.4)
      .moveTo(left, y + 16).lineTo(left + pageWidth, y + 16).stroke()
    y += 16
    pdf.y = y
  }
}

// ── Excel ──────────────────────────────────────────────────
export async function renderExcel(doc: ReportDocument, res: Response): Promise<void> {
  const wb = new ExcelJS.Workbook()
  wb.creator = 'Adani UAMS'
  wb.created = new Date()

  if (doc.tables.length === 0) {
    const ws = wb.addWorksheet('Report')
    ws.addRow([doc.title])
    ws.addRow(['No data available for the selected period.'])
  } else {
    doc.tables.forEach((table, idx) => {
      const sheetName = (table.title || `Sheet ${idx + 1}`).slice(0, 30).replace(/[\\/?*[\]]/g, ' ')
      const ws = wb.addWorksheet(sheetName)

      // Title row
      ws.addRow([doc.title]).getCell(1).font = { bold: true, size: 14, color: { argb: 'FF111827' } }
      ws.addRow([`${doc.asset.name}${doc.asset.serial ? `  ·  ${doc.asset.serial}` : ''}`])
      ws.addRow([`Period: ${fmtDate(doc.dateRange.from)} → ${fmtDate(doc.dateRange.to)}`])
      ws.addRow([])
      if (doc.tables.length > 1) {
        ws.addRow([table.title]).getCell(1).font = { bold: true, size: 12 }
        ws.addRow([])
      }

      // Header
      const headerRow = ws.addRow(table.columns.map(c => c.label))
      headerRow.font = { bold: true }
      headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } }
      headerRow.eachCell(cell => {
        cell.border = { bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } } }
        cell.alignment = { vertical: 'middle' }
      })

      // Data
      for (const row of table.rows) {
        const r = ws.addRow(table.columns.map(c => {
          const v = row[c.key]
          return v === null || v === undefined ? '' : v
        }))
        r.eachCell((cell, i) => {
          cell.alignment = { horizontal: table.columns[i - 1].align ?? 'left' }
        })
      }

      // Column widths
      ws.columns = table.columns.map(c => ({ width: Math.max(10, Math.round((c.width ?? 80) / 6)) }))

      // Freeze top header row
      ws.views = [{ state: 'frozen', ySplit: headerRow.number }]
    })
  }

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
  res.setHeader('Content-Disposition', `attachment; filename="${reportFilename(doc, 'xlsx')}"`)
  await wb.xlsx.write(res)
  res.end()
}

// ── CSV ────────────────────────────────────────────────────
function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return ''
  const s = String(v)
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`
  return s
}

export function renderCsv(doc: ReportDocument, res: Response): void {
  const lines: string[] = []
  lines.push(`"${doc.title}"`)
  lines.push(`"${doc.asset.name}${doc.asset.serial ? ` · ${doc.asset.serial}` : ''}"`)
  lines.push(`"Period: ${doc.dateRange.from} to ${doc.dateRange.to}"`)
  lines.push('')

  if (doc.tables.length === 0) {
    lines.push('"No data available for the selected period."')
  } else {
    doc.tables.forEach((table, idx) => {
      if (idx > 0) lines.push('')
      if (doc.tables.length > 1) lines.push(`"${table.title}"`)
      lines.push(table.columns.map(c => csvEscape(c.label)).join(','))
      for (const row of table.rows) {
        lines.push(table.columns.map(c => csvEscape(row[c.key])).join(','))
      }
    })
  }

  res.setHeader('Content-Type', 'text/csv; charset=utf-8')
  res.setHeader('Content-Disposition', `attachment; filename="${reportFilename(doc, 'csv')}"`)
  // BOM for Excel-friendly UTF-8
  res.write('﻿')
  res.write(lines.join('\r\n'))
  res.end()
}
